### ISSUE TITLE
问好

### ISSUE THREAD

**Issue by nobodxbodon** [hijiangtao/hijiangtao.github.io#9]
你好，有幸从 [独立博客列表](https://github.com/timqian/chinese-independent-blogs) 发现此仓库，添加到了 [此索引](https://gitee.com/zhishi/collection-of-chinese-blogs) 。

不知可否将此博客内容作为 [针对 md 格式的博客内容聚合工具](https://gitee.com/zhishi/collection-of-chinese-blogs/blob/master/%E6%96%87%E6%A1%A3/2021-01-26-%E5%9F%BA%E4%BA%8E%20git%20%E7%9A%84%E5%8D%9A%E5%AE%A2%E8%81%9A%E5%90%88%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF%EF%BC%88%E4%B8%80%EF%BC%89%EF%BC%9A%E8%AF%BB%E8%80%85.md) 的内容源之一？

**Comment by hijiangtao** [comment]
转载请注明作者和原文地址，谢谢关注。

**Comment by nobodxbodon** [comment]
谢谢支持。本工具打算在客户端运行，无额外网站服务。打算在显示博文时附上博客链接，如下：
![2021-02-10_链接示例](https://user-images.githubusercontent.com/392497/109622395-ea811580-7af0-11eb-9800-c25270a6a0e1.png)

已经同意将 git 仓库作为内容源的博主有十五个，一千二百多篇博文。现在搜集功能需求的过程中做一些简单脚本作技术调研。
进展 [在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)。欢迎任何意见建议。

**Comment by nobodxbodon** [comment]
报告一下，当前进展与待做小结在《[博客聚合原型进展：批量同步 git 仓库后生成本地网页及目录](https://gitee.com/zhishi/collection-of-chinese-blogs/blob/master/%E6%96%87%E6%A1%A3/2021-03-05-%E5%8D%9A%E5%AE%A2%E8%81%9A%E5%90%88%E5%8E%9F%E5%9E%8B%E8%BF%9B%E5%B1%95%EF%BC%9A%E6%89%B9%E9%87%8F%E5%90%8C%E6%AD%A5%20git%20%E4%BB%93%E5%BA%93%E5%90%8E%E7%94%9F%E6%88%90%E6%9C%AC%E5%9C%B0%E7%BD%91%E9%A1%B5%E5%8F%8A%E7%9B%AE%E5%BD%95.md)》。

**Comment by nobodxbodon** [comment]
龙年好！基于 [此设想](https://gitee.com/zhishi/collection-of-chinese-blogs/)，刚用gh pages搭了 [这个演示](http://nobodxbodon.github.io/)。博客同步、索引和网页内容生成等源码都 [在此](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B)。
现在仅有最基本的浏览功能，原文 url [还需要修](https://gitee.com/zhishi/collection-of-chinese-blogs/issues/I94K59)。
打算尽量定期更新内容并补充功能。
欢迎任何建议意见！

**Comment by nobodxbodon** [comment]
【今后 [在此issue](https://github.com/nobodxbodon/nobodxbodon.github.io/issues/1) 报告阶段进展，欢迎subscribe~】
原文链接已修正，添加了题目关键词搜索。
当前的聚合统计：
35 个博客、5826 篇博文, 占用空间 10.032 GB
